### ISSUE TITLE
Save link to clipboard instead of opening in browser

### ISSUE THREAD

**Issue by Brottweiler** [utecht/gimp_imgur#1]
I'd prefer to have the link be copied to my clipboard, and not have it open in my browser. Is that doable?

**Comment by Brottweiler** [comment]
I tried to use the [pyperclip](http://coffeeghost.net/2010/10/09/pyperclip-a-cross-platform-clipboard-module-for-python/) module, but as soon as I simply just add `import pyperclip`, and start GIMP, the script doesn't load in GIMP. Removing that line, makes it load.

**Comment by Brottweiler** [comment]
Figured it out, needed to "install" pyperclip to GIMP, or something. So I downloaded it and pasted it into `C:\Program Files\GIMP 2\Python\Lib` on Windows 7, which I am on right now.

**Comment by utecht** [comment]
Did you get it fully working?

Feel free to submit it as another script in a pull request and I'll merge it in, I'm sure other people could use it too.

**Comment by Brottweiler** [comment]
I got it working, using [pyperclip](http://coffeeghost.net/2010/10/09/pyperclip-a-cross-platform-clipboard-module-for-python/). So now when I am GNU/Linux, I had to download the [pyperclip.py](http://coffeeghost.net/src/pyperclip.py) file, and place it in `/usr/lib/gimp/2.0/python/`.

I forked your repo, and changed it from opening the browser, to copying to the clipboard. I replaced it, maybe it would work with some kind of config option, that you edit the `imgur-upload.py` and `imgur-flatten-upload.py` and change a variable from/to `TRUE`, to make it copy to clipboard instead of browser. Using an `if` statement.

Or maybe make a new branch for clipboard version? Not sure.

Edit: Oh you mean as another script, like having `imgur-upload-clipboard.py` and `imgur-flatten-upload-clipboard.py`?

**Comment by utecht** [comment]
Yea that's what I thinking, so you could either have multiple menu entries or people could just put whichever script they wanted.

**Comment by Brottweiler** [comment]
That's true! I will rename them and make a PR.

**Comment by Brottweiler** [comment]
#2 woo!
